version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    labels:
      - dependabot
      - dependencies
    groups:
      minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    labels:
      - dependabot
      - dependencies
    groups:
      minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
