name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  tests:
    uses: ebsnet/KeyGenFIPS/.github/workflows/build.yml@master

  publish:
    name: Publish build artifacts
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/distributions/KeyGenFIPS-*.tar
            ./build/distributions/KeyGenFIPS-*.zip

  changelog:
    name: Update Changelog
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
